# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew uninstall --ignore-dependencies python
        brew install python@3.9.20
        echo "================="
        python --version
        echo "================="
        python -m pip install --upgrade pip
        pip install buildozer
        pip install kivy
        pip install kivymd
        pip install Cython==0.29.33
        pip list -v
    - name: generate apk
      run: |
        buildozer -v android debug
